import { join, resolve } from "node:path"

export type DaemonConnectionState = "checking" | "connected" | "disconnected"

export type DaemonConnection = {
  state: DaemonConnectionState
  protocolVersion: string
  message: string
}

export type Fetcher = (input: string, init?: RequestInit) => Promise<Response>

let daemonTokenPromise: Promise<string> | undefined

async function daemonToken(): Promise<string> {
  const configured = process.env.ORKODA_API_TOKEN?.trim()
  if (configured) return configured
  for (const tokenPath of daemonTokenPaths()) {
    try {
      const token = (await Bun.file(tokenPath).text()).trim()
      if (token) return token
    } catch {
      // Try the next path so make tui can find the repository token after cd.
    }
  }
  return ""
}

function daemonTokenPaths(): string[] {
  const configuredFile = process.env.ORKODA_API_TOKEN_FILE?.trim()
  if (configuredFile) return pathCandidates(configuredFile)

  const dataDir = process.env.ORKODA_DATA_DIR?.trim()
  if (dataDir) return pathCandidates(join(dataDir, "api.token"))

  return pathCandidates(".orkoda/api.token")
}

function pathCandidates(path: string): string[] {
  const repositoryRootPath = resolve(import.meta.dir, "../../../", path)
  return [...new Set([path, repositoryRootPath])]
}

export async function requestWithDaemonAuth(
  fetcher: Fetcher,
  input: string,
  init: RequestInit = {},
): Promise<Response> {
  // Test callers and integrations may inject their own transport. Production
  // requests use the token generated by the local daemon.
  if (fetcher !== fetch) return fetcher(input, init)
  daemonTokenPromise ??= daemonToken()
  const token = await daemonTokenPromise
  if (!token) {
    daemonTokenPromise = undefined
    throw new Error(
      "Daemon API token not found. Start the daemon first or set ORKODA_API_TOKEN_FILE.",
    )
  }
  const headers = new Headers(init.headers)
  headers.set("authorization", `Bearer ${token}`)
  return fetcher(input, { ...init, headers })
}

type HealthResponse = {
  status?: unknown
  protocol_version?: unknown
}

export const daemonBaseURL = (process.env.ORKODA_DAEMON_URL ?? "http://127.0.0.1:8181").replace(
  /\/$/,
  "",
)

export const initialDaemonConnection: DaemonConnection = {
  state: "checking",
  protocolVersion: "v1",
  message: "Checking local daemon...",
}

export async function probeDaemon(
  baseURL = daemonBaseURL,
  fetcher: Fetcher = fetch,
): Promise<DaemonConnection> {
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), 1500)

  try {
    const response = await fetcher(`${baseURL}/health/live`, {
      headers: { accept: "application/json" },
      signal: controller.signal,
    })

    if (!response.ok) {
      return {
        state: "disconnected",
        protocolVersion: "v1",
        message: `Daemon returned HTTP ${response.status}`,
      }
    }

    const payload = (await response.json()) as HealthResponse
    if (payload.status !== "ok") {
      return {
        state: "disconnected",
        protocolVersion: "v1",
        message: "Daemon health response is invalid",
      }
    }

    return {
      state: "connected",
      protocolVersion:
        typeof payload.protocol_version === "string" ? payload.protocol_version : "v1",
      message: `Connected to ${baseURL}`,
    }
  } catch (error) {
    const message =
      error instanceof Error && error.name === "AbortError"
        ? "Daemon health check timed out"
        : "Daemon is not running"

    return {
      state: "disconnected",
      protocolVersion: "v1",
      message,
    }
  } finally {
    clearTimeout(timeout)
  }
}
