import { join, resolve } from "node:path"

export type DaemonConnectionState = "checking" | "connected" | "disconnected"

export type DaemonConnection = {
  state: DaemonConnectionState
  protocolVersion: string
  message: string
}

export type DiagnosticsSnapshot = {
  service: string
  status: "ready" | "degraded" | string
  protocol_version: string
  database: { integrity: string; schema_version: number }
  queue: { queued: number; running: number; dead: number }
  activity: { events: number; last_sequence: number }
  workspaces: { total: number; active_leases: number; expired_leases: number }
  generated_at: string
}

export type Fetcher = (input: string, init?: RequestInit) => Promise<Response>

let daemonTokenPromise: Promise<string> | undefined

async function daemonToken(): Promise<string> {
  const configured = process.env.ORKODA_API_TOKEN?.trim()
  if (configured) return configured
  for (const tokenPath of daemonTokenPaths()) {
    try {
      const token = (await Bun.file(tokenPath).text()).trim()
      if (token) return token
    } catch {
      // Try the next path so make tui can find the repository token after cd.
    }
  }
  return ""
}

function daemonTokenPaths(): string[] {
  const configuredFile = process.env.ORKODA_API_TOKEN_FILE?.trim()
  if (configuredFile) return pathCandidates(configuredFile)

  const dataDir = process.env.ORKODA_DATA_DIR?.trim()
  if (dataDir) return pathCandidates(join(dataDir, "api.token"))

  return pathCandidates(".orkoda/api.token")
}

function pathCandidates(path: string): string[] {
  const repositoryRootPath = resolve(import.meta.dir, "../../../", path)
  return [...new Set([path, repositoryRootPath])]
}

export async function requestWithDaemonAuth(
  fetcher: Fetcher,
  input: string,
  init: RequestInit = {},
): Promise<Response> {
  const headers = new Headers(init.headers)
  headers.set("x-request-id", headers.get("x-request-id") ?? newClientRequestID("req"))
  headers.set("x-correlation-id", headers.get("x-correlation-id") ?? newClientRequestID("corr"))
  if (init.method && !["GET", "HEAD", "OPTIONS"].includes(init.method.toUpperCase())) {
    headers.set("idempotency-key", headers.get("idempotency-key") ?? newClientRequestID("idem"))
  }
  // Test callers and integrations may inject their own transport. Production
  // requests use the token generated by the local daemon.
  if (fetcher !== fetch) return fetcher(input, { ...init, headers })
  daemonTokenPromise ??= daemonToken()
  const token = await daemonTokenPromise
  if (!token) {
    daemonTokenPromise = undefined
    throw new Error(
      "Daemon API token not found. Start the daemon first or set ORKODA_API_TOKEN_FILE.",
    )
  }
  headers.set("authorization", `Bearer ${token}`)
  return fetcher(input, { ...init, headers })
}

function newClientRequestID(prefix: string): string {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return `${prefix}-${crypto.randomUUID()}`
  }
  return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`
}

type HealthResponse = {
  status?: unknown
  protocol_version?: unknown
}

export const daemonBaseURL = (process.env.ORKODA_DAEMON_URL ?? "http://127.0.0.1:8181").replace(
  /\/$/,
  "",
)

export const initialDaemonConnection: DaemonConnection = {
  state: "checking",
  protocolVersion: "v1",
  message: "Checking local daemon...",
}

export async function probeDaemon(
  baseURL = daemonBaseURL,
  fetcher: Fetcher = fetch,
): Promise<DaemonConnection> {
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), 1500)

  try {
    const response = await fetcher(`${baseURL}/health/live`, {
      headers: { accept: "application/json" },
      signal: controller.signal,
    })

    if (!response.ok) {
      return {
        state: "disconnected",
        protocolVersion: "v1",
        message: `Daemon returned HTTP ${response.status}`,
      }
    }

    const payload = (await response.json()) as HealthResponse
    if (payload.status !== "ok") {
      return {
        state: "disconnected",
        protocolVersion: "v1",
        message: "Daemon health response is invalid",
      }
    }

    return {
      state: "connected",
      protocolVersion:
        typeof payload.protocol_version === "string" ? payload.protocol_version : "v1",
      message: `Connected to ${baseURL}`,
    }
  } catch (error) {
    const message =
      error instanceof Error && error.name === "AbortError"
        ? "Daemon health check timed out"
        : "Daemon is not running"

    return {
      state: "disconnected",
      protocolVersion: "v1",
      message,
    }
  } finally {
    clearTimeout(timeout)
  }
}

export async function getDiagnostics(fetcher: Fetcher = fetch): Promise<DiagnosticsSnapshot> {
  const response = await requestWithDaemonAuth(fetcher, `${daemonBaseURL}/api/v1/diagnostics`, {
    method: "GET",
    headers: { accept: "application/json" },
  })
  if (!response.ok) {
    throw new Error(`Diagnostics returned HTTP ${response.status}`)
  }
  const payload = (await response.json()) as { data?: DiagnosticsSnapshot }
  if (!payload.data) {
    throw new Error("Diagnostics response is invalid")
  }
  return payload.data
}

export async function createDiagnosticsBundle(fetcher: Fetcher = fetch): Promise<string> {
  const response = await requestWithDaemonAuth(
    fetcher,
    `${daemonBaseURL}/api/v1/diagnostics/bundle`,
    { method: "POST", headers: { accept: "application/json" } },
  )
  if (!response.ok) {
    throw new Error(`Diagnostics bundle returned HTTP ${response.status}`)
  }
  const payload = (await response.json()) as { data?: { artifact_key?: string } }
  const key = payload.data?.artifact_key
  if (!key) {
    throw new Error("Diagnostics bundle response is invalid")
  }
  return key
}
